<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.8" />
  </ItemGroup>

  <Target Name="CopyToPluginPool" AfterTargets="Build">
    <MakeDir Directories="$(SolutionDir)LazyLoad.Server\storage\plugins_pool" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SolutionDir)LazyLoad.Server\storage\plugins_pool" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(None)" Condition="'%(Extension)' == '.json'" DestinationFolder="$(SolutionDir)LazyLoad.Server\storage\plugins_pool" SkipUnchangedFiles="true" />
  </Target>

</Project>
